// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file vultisig/keygen/v1/reshare_message.proto (package vultisig.keygen.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { LibType } from "./lib_type_message_pb";
import { file_vultisig_keygen_v1_lib_type_message } from "./lib_type_message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vultisig/keygen/v1/reshare_message.proto.
 */
export const file_vultisig_keygen_v1_reshare_message: GenFile = /*@__PURE__*/
  fileDesc("Cih2dWx0aXNpZy9rZXlnZW4vdjEvcmVzaGFyZV9tZXNzYWdlLnByb3RvEhJ2dWx0aXNpZy5rZXlnZW4udjEimAIKDlJlc2hhcmVNZXNzYWdlEhIKCnNlc3Npb25faWQYASABKAkSFgoOaGV4X2NoYWluX2NvZGUYAiABKAkSFAoMc2VydmljZV9uYW1lGAMgASgJEhgKEHB1YmxpY19rZXlfZWNkc2EYBCABKAkSEwoLb2xkX3BhcnRpZXMYBSADKAkSGgoSZW5jcnlwdGlvbl9rZXlfaGV4GAYgASgJEhoKEnVzZV92dWx0aXNpZ19yZWxheRgHIAEoCBIaChJvbGRfcmVzaGFyZV9wcmVmaXgYCCABKAkSEgoKdmF1bHRfbmFtZRgJIAEoCRItCghsaWJfdHlwZRgUIAEoDjIbLnZ1bHRpc2lnLmtleWdlbi52MS5MaWJUeXBlQlIKEnZ1bHRpc2lnLmtleWdlbi52MVo3Z2l0aHViLmNvbS92dWx0aXNpZy9jb21tb25kYXRhL2dvL3Z1bHRpc2lnL2tleWdlbi92MTt2MboCAlZTYgZwcm90bzM", [file_vultisig_keygen_v1_lib_type_message]);

/**
 * @generated from message vultisig.keygen.v1.ReshareMessage
 */
export type ReshareMessage = Message<"vultisig.keygen.v1.ReshareMessage"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string hex_chain_code = 2;
   */
  hexChainCode: string;

  /**
   * @generated from field: string service_name = 3;
   */
  serviceName: string;

  /**
   * @generated from field: string public_key_ecdsa = 4;
   */
  publicKeyEcdsa: string;

  /**
   * @generated from field: repeated string old_parties = 5;
   */
  oldParties: string[];

  /**
   * @generated from field: string encryption_key_hex = 6;
   */
  encryptionKeyHex: string;

  /**
   * @generated from field: bool use_vultisig_relay = 7;
   */
  useVultisigRelay: boolean;

  /**
   * @generated from field: string old_reshare_prefix = 8;
   */
  oldResharePrefix: string;

  /**
   * @generated from field: string vault_name = 9;
   */
  vaultName: string;

  /**
   * Default to GG20
   *
   * @generated from field: vultisig.keygen.v1.LibType lib_type = 20;
   */
  libType: LibType;
};

/**
 * Describes the message vultisig.keygen.v1.ReshareMessage.
 * Use `create(ReshareMessageSchema)` to create a new message.
 */
export const ReshareMessageSchema: GenMessage<ReshareMessage> = /*@__PURE__*/
  messageDesc(file_vultisig_keygen_v1_reshare_message, 0);

