name: Flatpak build - Linux

on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Flatpak dependencies
        run: sudo apt-get update && sudo apt-get install -y flatpak flatpak-builder

      - name: Install Yarn dependencies
        run: yarn install --immutable

      - name: Build Flatpak
        run: |
          flatpak-builder --user --install-deps-from=flathub build-dir com.asgardex.asgardex-desktop.yml
          flatpak build-bundle build-dir asgardex.flatpak com.asgardex.asgardex-desktop stable
        env:
          NODE_OPTIONS: --max-old-space-size=7168
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_BLOCKCYPHER_API_KEY: ${{ secrets.REACT_APP_BLOCKCYPHER_API_KEY }}
          REACT_APP_ETHERSCAN_API_KEY: ${{ secrets.REACT_APP_ETHERSCAN_API_KEY }}
          REACT_APP_BSCSCAN_API_KEY: ${{ secrets.REACT_APP_BSCSCAN_API_KEY }}
          REACT_APP_ARBISCAN_API_KEY: ${{ secrets.REACT_APP_ARBISCAN_API_KEY }}
          REACT_APP_ASGARDEX_THORNAME: ${{ secrets.REACT_APP_ASGARDEX_THORNAME }}
          REACT_APP_BASE_API_KEY: ${{ secrets.REACT_APP_BASE_API_KEY }}
          REACT_APP_SNOWTRACE_API_KEY: ${{ secrets.REACT_APP_SNOWTRACE_API_KEY }}

      - name: Upload Flatpak artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-flatpak
          path: asgardex.flatpak

      - name: List Flatpak artifacts
        run: ls *.flatpak || echo "No Flatpak artifacts found"
